# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NewChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewChat
pod 'Alamofire', '~> 5.1'
pod 'SnapKit', '~> 5.0.0'
pod 'LeanCloud/Foundation'
pod 'LeanCloud/RTM'
pod 'SQLite.swift', '~> 0.12.0'

end
